export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"a","t":""},["/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"功能备份","i":"laptop-code"},["/demo/README.md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"目录","i":"lightbulb"},["/guide/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","t":"Bar 功能","i":"lightbulb"},["/guide/bar/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","t":"Foo 功能","i":"lightbulb"},["/guide/foo/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
