import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": 
  [
    {
      text: "天则指南",
      icon: "book",
      prefix: "guide/",
      link: "guide/",
      children: [
        "update.md",
        {
          text: "非想天启更新器说明",
          icon :"gears",
          prefix: "FXTQ/",
          collapsible: true,
          children: "structure",
        },
        {
          text: "问题指南",
          icon: "question",
          prefix: "FAQ/",
          collapsible: true,
          children: [
            {
              text: "游戏外问题",
              icon: "question",
              prefix: "Out-of-Games/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "游戏无法正常运行",
              icon: "question",
              prefix: "Failed-to-Start/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "游戏内问题",
              icon: "question",
              prefix: "In-Games/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "对战和大厅问题",
              icon: "question",
              prefix: "Play/",
              collapsible: true,
              children: "structure",
            }
          ],
        },
        {
          text: "MOD插件介绍",
          icon: "gear",
          prefix: "mods/",
          //link:"mods/",
          collapsible: true,
          children: [
            "WhatsMod.md",
            {
              text: "练习模式插件",
              icon: "file",
              prefix: "PracticeMods/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "联机相关插件",
              icon: "file",
              prefix: "NetMods/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "功能性插件",
              icon: "file",
              prefix: "QoLMods/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "游戏性Mod介绍",
              icon: "file",
              prefix: "GameplayMods/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "高级功能插件",
              icon: "file",
              prefix: "AdvancedMods/",
              collapsible: true,
              children: "structure",
            },
            {
              text: "修改素材Mod",
              icon: "file",
              prefix: "DIY/",
              collapsible: true,
              children: "structure",
            },
          ],
        }
      ],
    },



    {
      text: "游戏指南",
      icon: "book",
      prefix: "data/",
      link: "data/",
      children: [
        {
        text: "游戏系统",
        icon: "gears",
        prefix: "system/",
        collapsible: true,
        children: "structure",
        },
        {
          text: "机体数据",
          icon: "circle-info",
          prefix: "character/",
          collapsible: true,
          children: [
                    {
                      text: "全人类参考表",
                      icon: "book",
                      prefix: "All/",
                      collapsible: true,
                      children: "structure"
                    },
                    {
                    text: "博丽灵梦",
                    icon: "book",
                    prefix: "Reimu/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "雾雨魔理沙",
                    icon: "book",
                    prefix: "Marisa/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "爱丽丝·玛格特罗依德",
                    icon: "book",
                    prefix: "Alice/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "帕秋莉·诺蕾姬",
                    icon: "book",
                    prefix: "Patchouli/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "十六夜咲夜",
                    icon: "book",
                    prefix: "Sakuya/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "魂魄妖梦",
                    icon: "book",
                    prefix: "Youmu/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "蕾米莉亚·斯卡蕾特",
                    icon: "book",
                    prefix: "Remilia/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "西行寺幽幽子",
                    icon: "book",
                    prefix: "Yuyuko/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "八云紫",
                    icon: "book",
                    prefix: "Yukari/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "伊吹萃香",
                    icon: "book",
                    prefix: "Suika/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "铃仙·优昙华院·因幡",
                    icon: "book",
                    prefix: "Reisen/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "射命丸文",
                    icon: "book",
                    prefix: "Aya/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "小野塚小町",
                    icon: "book",
                    prefix: "Komachi/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "永江衣玖",
                    icon: "book",
                    prefix: "Iku/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                    text: "比那名居天子",
                    icon: "book",
                    prefix: "Tenshi/",
                    collapsible: true,
                    children: ["intro.md",
                              {
                                text: "招式数据",
                                icon: "book",
                                prefix: "moves/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "连段攻略",
                                icon: "book",
                                prefix: "combos/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "立回策略",
                                icon: "book",
                                prefix: "strategy/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "压制解析",
                                icon: "book",
                                prefix: "pressuring/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "实用技巧",
                                icon: "book",
                                prefix: "tips/",
                                collapsible: true,
                                children: "structure",
                              },
                              {
                                text: "机体对策",
                                icon: "book",
                                prefix: "countermeasures/",
                                collapsible: true,
                                children: "structure",
                              }]
                    },
                    {
                      text: "东风谷早苗",
                      icon: "book",
                      prefix: "Sanae/",
                      collapsible: true,
                      children: ["intro.md",
                                {
                                  text: "招式数据",
                                  icon: "book",
                                  prefix: "moves/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "连段攻略",
                                  icon: "book",
                                  prefix: "combos/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "立回策略",
                                  icon: "book",
                                  prefix: "strategy/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "压制解析",
                                  icon: "book",
                                  prefix: "pressuring/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "实用技巧",
                                  icon: "book",
                                  prefix: "tips/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "机体对策",
                                  icon: "book",
                                  prefix: "countermeasures/",
                                  collapsible: true,
                                  children: "structure",
                                }]
                      },
                      {
                      text: "琪露诺",
                      icon: "book",
                      prefix: "Cirno/",
                      collapsible: true,
                      children: ["intro.md",
                                {
                                  text: "招式数据",
                                  icon: "book",
                                  prefix: "moves/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "连段攻略",
                                  icon: "book",
                                  prefix: "combos/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "立回策略",
                                  icon: "book",
                                  prefix: "strategy/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "压制解析",
                                  icon: "book",
                                  prefix: "pressuring/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "实用技巧",
                                  icon: "book",
                                  prefix: "tips/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "机体对策",
                                  icon: "book",
                                  prefix: "countermeasures/",
                                  collapsible: true,
                                  children: "structure",
                                }]
                      },
                      {
                      text: "红美铃",
                      icon: "book",
                      prefix: "Meiling/",
                      collapsible: true,
                      children: ["intro.md",
                                {
                                  text: "招式数据",
                                  icon: "book",
                                  prefix: "moves/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "连段攻略",
                                  icon: "book",
                                  prefix: "combos/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "立回策略",
                                  icon: "book",
                                  prefix: "strategy/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "压制解析",
                                  icon: "book",
                                  prefix: "pressuring/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "实用技巧",
                                  icon: "book",
                                  prefix: "tips/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "机体对策",
                                  icon: "book",
                                  prefix: "countermeasures/",
                                  collapsible: true,
                                  children: "structure",
                                }]
                      },
                      {
                      text: "灵乌路空",
                      icon: "book",
                      prefix: "Kong/",
                      collapsible: true,
                      children: ["intro.md",
                                {
                                  text: "招式数据",
                                  icon: "book",
                                  prefix: "moves/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "连段攻略",
                                  icon: "book",
                                  prefix: "combos/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "立回策略",
                                  icon: "book",
                                  prefix: "strategy/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "压制解析",
                                  icon: "book",
                                  prefix: "pressuring/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "实用技巧",
                                  icon: "book",
                                  prefix: "tips/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "机体对策",
                                  icon: "book",
                                  prefix: "countermeasures/",
                                  collapsible: true,
                                  children: "structure",
                                }]
                      },
                      {
                      text: "洩矢诹访子",
                      icon: "book",
                      prefix: "Suwako/",
                      collapsible: true,
                      children: ["intro.md",
                                {
                                  text: "招式数据",
                                  icon: "book",
                                  prefix: "moves/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "连段攻略",
                                  icon: "book",
                                  prefix: "combos/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "立回策略",
                                  icon: "book",
                                  prefix: "strategy/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "压制解析",
                                  icon: "book",
                                  prefix: "pressuring/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "实用技巧",
                                  icon: "book",
                                  prefix: "tips/",
                                  collapsible: true,
                                  children: "structure",
                                },
                                {
                                  text: "机体对策",
                                  icon: "book",
                                  prefix: "countermeasures/",
                                  collapsible: true,
                                  children: "structure",
                                }]
                      },
                    ],
        }
      ],
    },



    {
      text: "记录",
      icon: "laptop-code",
      prefix: "demo/",
      link: "demo/",
      children: "structure",
    },
  ],
});
